aws:
  utils:
    region: us-west-1
    access-key-id: PLACEHOLDER
    access-key: PLACEHOLDER
  s3:
    bucket-name: puvs-89127fdgkh2-dev-bucket

server:
  port: 9211
spring:
  application:
    name: backend
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-consoles

